"""empty message

Revision ID: 014f2a9aece9
Revises: 2d7654ca87b6
Create Date: 2021-10-17 07:37:33.172470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '014f2a9aece9'
down_revision = '2d7654ca87b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('times_ran', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'times_ran')
    # ### end Alembic commands ###
