"""empty message

Revision ID: 063037b01c56
Revises: 8a80b51e3cee
Create Date: 2021-12-11 18:53:19.052293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063037b01c56'
down_revision = '8a80b51e3cee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_event', sa.Column('google_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_event', 'google_id')
    # ### end Alembic commands ###
