"""empty message

Revision ID: 08c7b79f57d5
Revises: 1bcf38c72b7a
Create Date: 2021-08-01 07:51:27.682282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c7b79f57d5'
down_revision = '1bcf38c72b7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense')
    op.add_column('transaction', sa.Column('category', sa.String(length=64), nullable=True))
    op.drop_column('transaction', 'img_url')
    op.drop_index('ix_user_email', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.add_column('transaction', sa.Column('img_url', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('transaction', 'category')
    op.create_table('expense',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('price_paid', sa.FLOAT(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
