"""empty message

Revision ID: 0f7b28a7a1e3
Revises: c2c9d1334758
Create Date: 2021-11-08 11:15:04.512725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f7b28a7a1e3'
down_revision = 'c2c9d1334758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lap_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('milliseconds', sa.Integer(), nullable=True),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('dnf', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['owned_car.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lap_time')
    # ### end Alembic commands ###
