"""empty message

Revision ID: 10bd52b06872
Revises: f14c2f9ab921
Create Date: 2021-08-25 10:39:07.087398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10bd52b06872'
down_revision = 'f14c2f9ab921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('blackjack', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'blackjack')
    # ### end Alembic commands ###
