"""empty message

Revision ID: 158d7e520933
Revises: 416962d00e0b
Create Date: 2021-11-17 04:44:19.988563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '158d7e520933'
down_revision = '416962d00e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement', sa.Column('point_value', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievement', 'point_value')
    # ### end Alembic commands ###
