"""empty message

Revision ID: 1bcf38c72b7a
Revises: 79e4fbec6640
Create Date: 2021-08-01 04:20:13.402933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bcf38c72b7a'
down_revision = '79e4fbec6640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'quantity')
    # ### end Alembic commands ###
