"""empty message

Revision ID: 1c3ff1e1ad47
Revises: 5e54e8e06d96
Create Date: 2021-08-18 08:33:16.177492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c3ff1e1ad47'
down_revision = '5e54e8e06d96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fishing_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('misc', sa.Integer(), nullable=True),
    sa.Column('fish', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fishing_entry_timestamp'), 'fishing_entry', ['timestamp'], unique=False)
    op.create_table('hunting_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.Column('collateral', sa.Boolean(), nullable=True),
    sa.Column('meat', sa.Integer(), nullable=True),
    sa.Column('small_pelt', sa.Integer(), nullable=True),
    sa.Column('med_pelt', sa.Integer(), nullable=True),
    sa.Column('large_pelt', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hunting_entry_timestamp'), 'hunting_entry', ['timestamp'], unique=False)
    op.add_column('company', sa.Column('access_token', sa.String(length=128), nullable=True))
    op.add_column('transaction', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transaction', 'order', ['order_id'], ['id'])
    op.add_column('user', sa.Column('sub_expiration', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sub_expiration')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'order_id')
    op.drop_column('company', 'access_token')
    op.drop_index(op.f('ix_hunting_entry_timestamp'), table_name='hunting_entry')
    op.drop_table('hunting_entry')
    op.drop_index(op.f('ix_fishing_entry_timestamp'), table_name='fishing_entry')
    op.drop_table('fishing_entry')
    op.drop_table('order')
    op.drop_table('job')
    # ### end Alembic commands ###
