"""empty message

Revision ID: 202c2c66b3ad
Revises: 08c7b79f57d5
Create Date: 2021-08-01 10:28:43.801050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202c2c66b3ad'
down_revision = '08c7b79f57d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'category')
    op.add_column('transaction', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('transaction', sa.Column('details', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'details')
    op.drop_column('transaction', 'name')
    op.add_column('product', sa.Column('category', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
