"""empty message

Revision ID: 2d7654ca87b6
Revises: f7ef020a6e12
Create Date: 2021-10-17 07:17:25.316212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d7654ca87b6'
down_revision = 'f7ef020a6e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owned_car', sa.Column('first', sa.Integer(), nullable=True))
    op.add_column('owned_car', sa.Column('second', sa.Integer(), nullable=True))
    op.add_column('owned_car', sa.Column('third', sa.Integer(), nullable=True))
    op.add_column('owned_car', sa.Column('races', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owned_car', 'races')
    op.drop_column('owned_car', 'third')
    op.drop_column('owned_car', 'second')
    op.drop_column('owned_car', 'first')
    # ### end Alembic commands ###
