"""empty message

Revision ID: 324ab5a44331
Revises: bc79206537e7
Create Date: 2021-10-17 00:34:25.518250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324ab5a44331'
down_revision = 'bc79206537e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('track_map', sa.String(length=256), nullable=True))
    op.add_column('track', sa.Column('track_video', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'track_video')
    op.drop_column('track', 'track_map')
    # ### end Alembic commands ###
