"""empty message

Revision ID: 36e5b2462ab2
Revises: 370f25f1b39e
Create Date: 2021-10-22 12:44:09.331413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e5b2462ab2'
down_revision = '370f25f1b39e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('crew_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'track', 'crew', ['crew_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'track', type_='foreignkey')
    op.drop_column('track', 'crew_id')
    # ### end Alembic commands ###
