"""empty message

Revision ID: 370f25f1b39e
Revises: 4fe034e8487a
Create Date: 2021-10-21 14:02:57.126648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '370f25f1b39e'
down_revision = '4fe034e8487a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('buyin', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('race', 'buyin')
    # ### end Alembic commands ###
