"""empty message

Revision ID: 4cb5dcf1b43d
Revises: db3d1678946c
Create Date: 2021-10-24 13:07:44.411599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb5dcf1b43d'
down_revision = 'db3d1678946c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('challenging_crew_id', sa.Integer(), nullable=True))
    op.add_column('race', sa.Column('defending_crew_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'race', 'crew', ['defending_crew_id'], ['id'])
    op.create_foreign_key(None, 'race', 'crew', ['challenging_crew_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'race', type_='foreignkey')
    op.drop_constraint(None, 'race', type_='foreignkey')
    op.drop_column('race', 'defending_crew_id')
    op.drop_column('race', 'challenging_crew_id')
    # ### end Alembic commands ###
