"""empty message

Revision ID: 522cbf903158
Revises: 577055ed7da4
Create Date: 2021-08-19 02:24:19.719731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522cbf903158'
down_revision = '577055ed7da4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('total_earnings', sa.String(length=64), nullable=True))
    op.add_column('job', sa.Column('hourly_earnings', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'hourly_earnings')
    op.drop_column('job', 'total_earnings')
    # ### end Alembic commands ###
