"""empty message

Revision ID: 54d649762866
Revises: 18efd7089c44
Create Date: 2021-07-31 07:32:12.286282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d649762866'
down_revision = '18efd7089c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('img_url', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'img_url')
    # ### end Alembic commands ###
