"""empty message

Revision ID: 577055ed7da4
Revises: 732b6fffe866
Create Date: 2021-08-19 02:09:56.472249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577055ed7da4'
down_revision = '732b6fffe866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_job_timestamp'), 'job', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_timestamp'), table_name='job')
    op.drop_column('job', 'timestamp')
    # ### end Alembic commands ###
