"""empty message

Revision ID: 596cac2bba57
Revises: f794c4289241
Create Date: 2021-10-20 09:10:02.476642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596cac2bba57'
down_revision = 'f794c4289241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crew', sa.Column('image', sa.String(length=256), nullable=True))
    op.add_column('crew', sa.Column('track_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'crew', 'track', ['track_id'], ['id'])
    op.add_column('track', sa.Column('race_org', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'race_org')
    op.drop_constraint(None, 'crew', type_='foreignkey')
    op.drop_column('crew', 'track_id')
    op.drop_column('crew', 'image')
    # ### end Alembic commands ###
