"""empty message

Revision ID: 5b5ae2885b42
Revises: c9af150e3e55
Create Date: 2021-08-23 20:46:26.371041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b5ae2885b42'
down_revision = 'c9af150e3e55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('personal', sa.Boolean(), nullable=True))
    op.add_column('transaction', sa.Column('business', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('auto_renew', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('personal', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('business', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'business')
    op.drop_column('user', 'personal')
    op.drop_column('user', 'auto_renew')
    op.drop_column('transaction', 'business')
    op.drop_column('transaction', 'personal')
    # ### end Alembic commands ###
