"""empty message

Revision ID: 6f3519944de3
Revises: 78c7c508ddf7
Create Date: 2022-02-17 23:16:20.990541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f3519944de3'
down_revision = '78c7c508ddf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('srp', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'srp')
    # ### end Alembic commands ###
