"""empty message

Revision ID: 716dfbf92478
Revises: 15b229fb42cd
Create Date: 2021-07-31 17:24:01.782357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716dfbf92478'
down_revision = '15b229fb42cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('img_url', sa.String(length=140), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price_paid', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('inventory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('price_paid', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('expense')
    # ### end Alembic commands ###
