"""empty message

Revision ID: 78c7c508ddf7
Revises: 063037b01c56
Create Date: 2021-12-14 17:10:30.890338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78c7c508ddf7'
down_revision = '063037b01c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_event', sa.Column('author_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_event', 'author_name')
    # ### end Alembic commands ###
