"""empty message

Revision ID: 78ee3d5dc27a
Revises: 94ec7519d871
Create Date: 2021-08-20 14:00:42.951726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ee3d5dc27a'
down_revision = '94ec7519d871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fishing_entry', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fishing_entry', 'user', ['user_id'], ['id'])
    op.add_column('hunting_entry', sa.Column('sell_value', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hunting_entry', 'sell_value')
    op.drop_constraint(None, 'fishing_entry', type_='foreignkey')
    op.drop_column('fishing_entry', 'user_id')
    # ### end Alembic commands ###
