"""empty message

Revision ID: 79a34dc99773
Revises: f03a127916f9
Create Date: 2021-07-31 09:10:07.476066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79a34dc99773'
down_revision = 'f03a127916f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('img_url', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'img_url')
    # ### end Alembic commands ###
