"""empty message

Revision ID: 7a38d60fdf0e
Revises: 5b5ae2885b42
Create Date: 2021-08-25 08:29:01.984684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a38d60fdf0e'
down_revision = '5b5ae2885b42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blackjack_hand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('s_2', sa.Boolean(), nullable=True),
    sa.Column('s_3', sa.Boolean(), nullable=True),
    sa.Column('s_4', sa.Boolean(), nullable=True),
    sa.Column('s_5', sa.Boolean(), nullable=True),
    sa.Column('s_6', sa.Boolean(), nullable=True),
    sa.Column('s_7', sa.Boolean(), nullable=True),
    sa.Column('s_8', sa.Boolean(), nullable=True),
    sa.Column('s_9', sa.Boolean(), nullable=True),
    sa.Column('s_t', sa.Boolean(), nullable=True),
    sa.Column('s_j', sa.Boolean(), nullable=True),
    sa.Column('s_q', sa.Boolean(), nullable=True),
    sa.Column('s_k', sa.Boolean(), nullable=True),
    sa.Column('c_2', sa.Boolean(), nullable=True),
    sa.Column('c_3', sa.Boolean(), nullable=True),
    sa.Column('c_4', sa.Boolean(), nullable=True),
    sa.Column('c_5', sa.Boolean(), nullable=True),
    sa.Column('c_6', sa.Boolean(), nullable=True),
    sa.Column('c_7', sa.Boolean(), nullable=True),
    sa.Column('c_8', sa.Boolean(), nullable=True),
    sa.Column('c_9', sa.Boolean(), nullable=True),
    sa.Column('c_t', sa.Boolean(), nullable=True),
    sa.Column('c_j', sa.Boolean(), nullable=True),
    sa.Column('c_q', sa.Boolean(), nullable=True),
    sa.Column('c_k', sa.Boolean(), nullable=True),
    sa.Column('d_2', sa.Boolean(), nullable=True),
    sa.Column('d_3', sa.Boolean(), nullable=True),
    sa.Column('d_4', sa.Boolean(), nullable=True),
    sa.Column('d_5', sa.Boolean(), nullable=True),
    sa.Column('d_6', sa.Boolean(), nullable=True),
    sa.Column('d_7', sa.Boolean(), nullable=True),
    sa.Column('d_8', sa.Boolean(), nullable=True),
    sa.Column('d_9', sa.Boolean(), nullable=True),
    sa.Column('d_t', sa.Boolean(), nullable=True),
    sa.Column('d_j', sa.Boolean(), nullable=True),
    sa.Column('d_q', sa.Boolean(), nullable=True),
    sa.Column('d_k', sa.Boolean(), nullable=True),
    sa.Column('h_2', sa.Boolean(), nullable=True),
    sa.Column('h_3', sa.Boolean(), nullable=True),
    sa.Column('h_4', sa.Boolean(), nullable=True),
    sa.Column('h_5', sa.Boolean(), nullable=True),
    sa.Column('h_6', sa.Boolean(), nullable=True),
    sa.Column('h_7', sa.Boolean(), nullable=True),
    sa.Column('h_8', sa.Boolean(), nullable=True),
    sa.Column('h_9', sa.Boolean(), nullable=True),
    sa.Column('h_t', sa.Boolean(), nullable=True),
    sa.Column('h_j', sa.Boolean(), nullable=True),
    sa.Column('h_q', sa.Boolean(), nullable=True),
    sa.Column('h_k', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blackjack_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blackjack_hand', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('job', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('player_hand', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['blackjack_hand'], ['blackjack_hand.id'], ),
    sa.ForeignKeyConstraint(['job'], ['job.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blackjack_entry_timestamp'), 'blackjack_entry', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blackjack_entry_timestamp'), table_name='blackjack_entry')
    op.drop_table('blackjack_entry')
    op.drop_table('blackjack_hand')
    # ### end Alembic commands ###
