"""empty message

Revision ID: 8a18080006cc
Revises: 014f2a9aece9
Create Date: 2021-10-17 20:00:06.535123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a18080006cc'
down_revision = '014f2a9aece9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('embed_link', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'embed_link')
    # ### end Alembic commands ###
