"""empty message

Revision ID: 8a80b51e3cee
Revises: 7ded004b1996
Create Date: 2021-12-10 13:39:47.230533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a80b51e3cee'
down_revision = '7ded004b1996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nd', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'nd')
    # ### end Alembic commands ###
