"""empty message

Revision ID: 9478b692284f
Revises: b06637381390
Create Date: 2021-11-07 01:22:21.569814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9478b692284f'
down_revision = 'b06637381390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement_condition', sa.Column('car_class_info', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievement_condition', 'car_class_info')
    # ### end Alembic commands ###
