"""empty message

Revision ID: 94ec7519d871
Revises: 522cbf903158
Create Date: 2021-08-19 09:19:15.313746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ec7519d871'
down_revision = '522cbf903158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hunter', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('fisher', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'fisher')
    op.drop_column('user', 'hunter')
    # ### end Alembic commands ###
