"""empty message

Revision ID: a20a09c0d02b
Revises: 716dfbf92478
Create Date: 2021-07-31 17:26:31.576676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a20a09c0d02b'
down_revision = '716dfbf92478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense', 'img_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('img_url', sa.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###
