"""empty message

Revision ID: a5eb27eb36d6
Revises: 30e36ba2d485
Create Date: 2021-08-05 09:58:40.531847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5eb27eb36d6'
down_revision = '30e36ba2d485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dark_mode', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'dark_mode')
    # ### end Alembic commands ###
