"""empty message

Revision ID: aeacf40f77a6
Revises: 79a34dc99773
Create Date: 2021-07-31 10:19:45.774127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeacf40f77a6'
down_revision = '79a34dc99773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'price')
    # ### end Alembic commands ###
