"""empty message

Revision ID: b06637381390
Revises: e3d9af3186d4
Create Date: 2021-11-06 16:00:17.886887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b06637381390'
down_revision = 'e3d9af3186d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement', sa.Column('achievement_category', sa.String(length=256), nullable=True))
    op.drop_column('achievement', 'achievement_type')
    op.add_column('achievement_condition', sa.Column('achievement_type', sa.String(length=64), nullable=True))
    op.add_column('achievement_condition', sa.Column('value', sa.Integer(), nullable=True))
    op.add_column('achievement_condition', sa.Column('operand', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('race_host', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'race_host')
    op.drop_column('achievement_condition', 'operand')
    op.drop_column('achievement_condition', 'value')
    op.drop_column('achievement_condition', 'achievement_type')
    op.add_column('achievement', sa.Column('achievement_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('achievement', 'achievement_category')
    # ### end Alembic commands ###
