"""empty message

Revision ID: c2c9d1334758
Revises: 7e8255f857c8
Create Date: 2021-11-07 11:45:38.003687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2c9d1334758'
down_revision = '7e8255f857c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race_performance', sa.Column('payout', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('race_performance', 'payout')
    # ### end Alembic commands ###
