"""empty message

Revision ID: c9af150e3e55
Revises: 78ee3d5dc27a
Create Date: 2021-08-21 18:05:59.666671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9af150e3e55'
down_revision = '78ee3d5dc27a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postal_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('no_pay', sa.Boolean(), nullable=True),
    sa.Column('sell_value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job'], ['job.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postal_entry_timestamp'), 'postal_entry', ['timestamp'], unique=False)
    op.add_column('fishing_entry', sa.Column('sell_value', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('postal', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('miner', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'miner')
    op.drop_column('user', 'postal')
    op.drop_column('fishing_entry', 'sell_value')
    op.drop_index(op.f('ix_postal_entry_timestamp'), table_name='postal_entry')
    op.drop_table('postal_entry')
    # ### end Alembic commands ###
