"""empty message

Revision ID: db3d1678946c
Revises: 36e5b2462ab2
Create Date: 2021-10-23 21:24:58.097835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db3d1678946c'
down_revision = '36e5b2462ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crew_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('challenging_crew', sa.Integer(), nullable=True),
    sa.Column('defending_crew', sa.Integer(), nullable=True),
    sa.Column('challenging_crew_points', sa.Integer(), nullable=True),
    sa.Column('defending_crew_points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['challenging_crew'], ['crew.id'], ),
    sa.ForeignKeyConstraint(['defending_crew'], ['crew.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('race', sa.Column('octane_member', sa.Boolean(), nullable=True))
    op.add_column('race', sa.Column('octane_prospect', sa.Boolean(), nullable=True))
    op.add_column('race', sa.Column('octane_crew', sa.Boolean(), nullable=True))
    op.add_column('race', sa.Column('open_249', sa.Boolean(), nullable=True))
    op.add_column('race', sa.Column('new_blood_249', sa.Boolean(), nullable=True))
    op.add_column('race', sa.Column('offroad_249', sa.Boolean(), nullable=True))
    op.add_column('race', sa.Column('moto_249', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('race', 'moto_249')
    op.drop_column('race', 'offroad_249')
    op.drop_column('race', 'new_blood_249')
    op.drop_column('race', 'open_249')
    op.drop_column('race', 'octane_crew')
    op.drop_column('race', 'octane_prospect')
    op.drop_column('race', 'octane_member')
    op.drop_table('crew_results')
    # ### end Alembic commands ###
