"""empty message

Revision ID: e3d9af3186d4
Revises: 3c897a91ad5d
Create Date: 2021-11-04 14:32:10.046600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d9af3186d4'
down_revision = '3c897a91ad5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('octane_newcomer', sa.Boolean(), nullable=True))
    op.add_column('race', sa.Column('octane_community', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('race', 'octane_community')
    op.drop_column('race', 'octane_newcomer')
    # ### end Alembic commands ###
