"""empty message

Revision ID: f03a127916f9
Revises: 54d649762866
Create Date: 2021-07-31 07:55:31.351530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f03a127916f9'
down_revision = '54d649762866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('product_name', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'product_name')
    # ### end Alembic commands ###
