"""empty message

Revision ID: f14c2f9ab921
Revises: 7a38d60fdf0e
Create Date: 2021-08-25 09:46:44.341873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f14c2f9ab921'
down_revision = '7a38d60fdf0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blackjack_entry_blackjack_hand_fkey', 'blackjack_entry', type_='foreignkey')
    op.drop_column('blackjack_entry', 'player_hand')
    op.drop_column('blackjack_entry', 'blackjack_hand')
    op.add_column('blackjack_hand', sa.Column('blackjack_entry', sa.Integer(), nullable=True))
    op.add_column('blackjack_hand', sa.Column('player_hand', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'blackjack_hand', 'blackjack_entry', ['blackjack_entry'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blackjack_hand', type_='foreignkey')
    op.drop_column('blackjack_hand', 'player_hand')
    op.drop_column('blackjack_hand', 'blackjack_entry')
    op.add_column('blackjack_entry', sa.Column('blackjack_hand', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('blackjack_entry', sa.Column('player_hand', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_foreign_key('blackjack_entry_blackjack_hand_fkey', 'blackjack_entry', 'blackjack_hand', ['blackjack_hand'], ['id'])
    # ### end Alembic commands ###
