"""empty message

Revision ID: f794c4289241
Revises: fe252302d832
Create Date: 2021-10-20 04:58:19.420675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f794c4289241'
down_revision = 'fe252302d832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crew',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('crew_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'crew', ['crew_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'crew_id')
    op.drop_table('crew')
    # ### end Alembic commands ###
