"""empty message

Revision ID: fe252302d832
Revises: 8a18080006cc
Create Date: 2021-10-20 00:11:22.764643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe252302d832'
down_revision = '8a18080006cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('finalized', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('race', 'finalized')
    # ### end Alembic commands ###
